complexity:
  LongMethod:
    ignoreAnnotated: ["Composable"]
  LongParameterList:
    active: true
    ignoreAnnotated: ["Composable"]
    constructorThreshold: 8
    functionThreshold: 8
  TooManyFunctions:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  ReturnCount:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: ["Preview"]

naming:
  # Allow PascalCase for @Composable UI functions
  FunctionNaming:
    ignoreAnnotated: ["Composable"]

exceptions:
  TooGenericExceptionCaught:
    active: false
